"""Remove project owner id.

Revision ID: bf1b64e1ccdd
Revises: d270d0bce7f6
Create Date: 2026-09-20 16:46:48.157334
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision: str = "bf1b64e1ccdd"
down_revision: str | Sequence[str] | None = "d270d0bce7f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_projects_owner_id"),
        table_name="projects",
    )
    op.drop_column(
        "projects",
        "owner_id",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "owner_id",
            sa.UUID(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_projects_owner_id"),
        "projects",
        ["owner_id"],
        unique=False,
    )
    # ### end Alembic commands ###
