"""Add project ownership and access.

Revision ID: d270d0bce7f6
Revises: efcb63702631
Create Date: 2026-09-17 18:45:25.737926
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.

revision: str = "d270d0bce7f6"
down_revision: str | Sequence[str] | None = "efcb63702631"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_access",
        sa.Column(
            "project_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum(
                "OWNER",
                "ADMIN",
                "DEVELOPER",
                "VIEWER",
                name="project_role",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id",
            "user_id",
        ),
    )

    op.add_column(
        "projects",
        sa.Column(
            "owner_id",
            sa.Uuid(),
            nullable=False,
        ),
    )

    op.create_index(
        op.f("ix_projects_owner_id"),
        "projects",
        ["owner_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_projects_owner_id"),
        table_name="projects",
    )
    op.drop_column(
        "projects",
        "owner_id",
    )
    op.drop_table("project_access")
    # ### end Alembic commands ###
